# Generated by Django 4.1.3 on 2022-11-15 07:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_stuba', models.CharField(max_length=100)),
                ('lokacija', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('adresa', models.CharField(max_length=100)),
                ('grad', models.CharField(max_length=50)),
                ('konzola', models.CharField(max_length=100)),
                ('izolator', models.CharField(max_length=100)),
                ('provodnik', models.CharField(max_length=100)),
            ],
        ),
    ]
